### ISSUE TITLE
Invoice PDF Generation

### ISSUE THREAD

**Issue by ejsenn** [coreshop/CoreShop#374] opened 2018-03-23 10:42 UTC
Hello,

I'm running currently into the following issue. On a fresh Pimcore 5 & Coreshop 2 (dev/master) install, we're unable to generate pdf invoice. wkhtmltopdf is install and on the command line it's working without any issue. Inside the Orders Detail view, if I open a generated Invoice (pdf) i receive the error message that the pdf might can't be loaded (i just see a dark grey background) and if i try to load the pdf inside Acrobat Reader it tell's me that the file might be broken or incompatible.

Any ideas on that matter ? Something where i can take look maybe (special logs or something?!).
Thanks in advance - Kind Regards

**Comment by dpfaffenbauer** [comment] 2018-03-26 08:52
I can't reproduce your issue, can you maybe check the logs for errors?

**Comment by ejsenn** [comment] 2018-03-27 15:43
I just found the problem, as well as the solution ...
I'm using serverside Ubuntu 16.04 LTS ... Since Ubuntu is based on Debian both systems have the same problems. There is a documented bugs in debian based systems and wkhtmltopdf. The version in the repositories are not ment to run headless. you need xvfb-run command with it ...

Set (in properties) the wkhtmltopdf binary as follow: /usr/bin/xvfb-run /usr/bin/wkhtmltopdf

after this change ... it's running smoothly !

**Comment by dpfaffenbauer** [comment] 2018-03-27 17:04
Better you change the configuration inside your app/config/parameters.yml. Can you try that as well?

**Comment by ejsenn** [comment] 2018-03-27 17:08
i did - that wasn't working out (first thought)

**Comment by dpfaffenbauer** [comment] 2018-03-27 17:19
Guess pimcore does something odd there as well.... 

Can you try installing a reliable installation of wkhtmltopdf like I do with my composer images?

https://github.com/dpfaffenbauer/pimcore-docker-php-fpm/blob/master/PHP7-apache/Dockerfile#L22

**Comment by dpfaffenbauer** [comment] 2018-03-28 15:13
closing this due to an configuration issue/pimcore issue.

**Closed by dpfaffenbauer** 2018-03-28 15:13 UTC
Labels: bug, coreshop2
