### ISSUE TITLE
Can't setStorePrice on variants

### ISSUE THREAD

**Issue by D37R4C7** [coreshop/CoreShop#1088] opened 2019-09-05 08:21 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Pimcore Version: 6.1.2
CoreShop Version: 67436393151b73969d4d19d3032dc3ddc2393f0f

Create a CoreShopProduct by code and setStorePrice to 0.

Create another CoreShopProduct by code, setStorePrice to 1000 and setVariant to previous created product as parent.

save()

This will update the price of the parent, while variant has no price.

---------------------

Create a CoreShopProduct by code and setStorePrice to 0.

Create another CoreShopProduct by code, setStorePrice to 1000 

save()

Now setVariant to previous created product as parent.

save()

This will update the price of the variant.

---------------------

Why is the first verison not working?

**Comment by dpfaffenbauer** [comment] 2019-09-05 12:57
OK, just tried it, this is what I did:

```php
$product = CoreShopProduct::getByPath('/test/blub');

if (!$product) {
    $product = new CoreShopProduct();
    $product->setParent(Service::createFolderByPath('/test'));
    $product->setKey('blub');
}

$store = \Pimcore::getContainer()->get('coreshop.repository.store')->findStandard();

$product->setStorePrice(0, $store);
$product->save();

$variant = CoreShopProduct::getByPath('/test/blub/variant');

if (!$variant) {
    $variant = new CoreShopProduct();
    $variant->setParent($product);
    $variant->setKey('variant');
    $variant->setType('variant');
}

$variant->setStorePrice(10000, $store);
$variant->save();

return 0;
```

and it works....

**Comment by D37R4C7** [comment] 2019-09-06 09:12
This one is not working... What do I do wrong?

```
        // First and only entry in data
        $isMaster = ((int)$data['LoadCapacity'] == 0);

        if ($isMaster) {

            $product = new CoreShopProduct();
            $product->setParent(Service::createFolderByPath('/test/'));
            $product->setKey('blub');

            $product->setStorePrice(10, $this->storeRepository->findStandard());
            $product->save();
        }
        else {
            $variant = new CoreShopProduct();
            $variant->setParent(CoreShopProduct::getByPath('/blub'));
            $variant->setKey(uniqid());
            $variant->setType('variant');

            $variant->setStorePrice(10000, $this->storeRepository->findStandard());
            $variant->save();
        }

        return;
```

**Comment by dpfaffenbauer** [comment] 2019-09-06 09:20
the variants has to be a child of the object. so try it like this:

```php
 // First and only entry in data
    $isMaster = ((int)$data['LoadCapacity'] == 0);

    if ($isMaster) {
        $product = new CoreShopProduct();
        $product->setParent(Service::createFolderByPath('/test/'));
        $product->setKey('blub');

        $product->setStorePrice(10, $this->storeRepository->findStandard());
        $product->save();
    }
    else {
        $variant = new CoreShopProduct();
        $variant->setParent(CoreShopProduct::getByPath('/test/blub'));
        $variant->setKey(uniqid());
        $variant->setType('variant');

        $variant->setStorePrice(10000, $this->storeRepository->findStandard());
        $variant->save();
    }

    return;
```

**Comment by dpfaffenbauer** [comment] 2019-09-06 09:20
only difference is in `$variant->setParent`

**Comment by D37R4C7** [comment] 2019-09-06 09:49
Tried that already and I know it is strange... But this is the result...

```
In AbstractObject.php line 747:
                                                                           
ParentID and ID is identical, an element can't be the parent of itself.  
```

By the way... My blub object is stored under / and not in a folder called test, what I thought would happen.

**Comment by dpfaffenbauer** [comment] 2019-09-07 08:26
no its not, it is stored unter /test:

`$product->setParent(Service::createFolderByPath('/test/'));`

Also, the error only comes when you actually set parent to itself... which it doesn't seem to do using my scenario.

**Comment by dpfaffenbauer** [comment] 2019-09-11 13:26
just for reference, we debugged it, the issue is: if you have multiple stores setup, but don't define a price for it, it will silently fail and not insert into the store values table

**Comment by dpfaffenbauer** [comment] 2019-09-12 05:54
fix has been merged, please pull dev-master and test if it works for you now.

**Closed** 2019-09-12 05:55 UTC
