### ISSUE TITLE
Cannot pass to payment step

### ISSUE THREAD

**Issue by tymon82** [coreshop/CoreShop#1068] opened 2019-08-08 11:45 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

After update i have problem with checkout step address - after submit i got 302 from payment back to address.

i've checked that cart object does not have set setInvoiceAddress (null value) even post data is right.

**Comment by dpfaffenbauer** [comment] 2019-08-08 11:53
any customizations you made?

**Comment by tymon82** [comment] 2019-08-08 11:54
no im on original checkout from demo version.

**Comment by tymon82** [comment] 2019-08-08 11:57
passing in request `invoiceAddress | 57` variable

**Comment by dpfaffenbauer** [comment] 2019-08-08 11:57
but it works on demo2.coreshop.org

**Comment by macmastermike** [comment] 2019-08-10 11:51
i think i have the same problem (v2.0.8) - after creating a shipping adress and selecting it i can't continue....

This value is not valid. 
shippingAddress | Caused by:ConstraintViolation 
{#4825 ▼   root: Form {#4804 …}   
path: "children[shippingAddress]"   value: "114" }

Path | children[shippingAddress]
Message | This value is not valid.
Invalid value | "114"

**Comment by dpfaffenbauer** [comment] 2019-08-10 12:11
What Pimcore Version do you guys use?

**Comment by dpfaffenbauer** [comment] 2019-08-10 12:11
Is the created Address published?

**Comment by macmastermike** [comment] 2019-08-10 12:48
seems when i create an address in coreshop via registration it works. the manually created data object in the pimcore admin didn't (but it was in the /coreshop/customer folder - not the /co/cu/A-Z etc).
works fine for me now!

**Comment by dpfaffenbauer** [comment] 2019-08-10 18:54
it doesnt matter for pimcore where you add the adress, just make sure its assigned to the customer object and that it is published.

**Comment by dpfaffenbauer** [comment] 2019-08-12 07:54
@tymon82 I guess its a user issue and not a CoreShop Issue. If you still feel it is a bug and you need more help, feel free to comment here again. I will close it for now.

**Closed by dpfaffenbauer** 2019-08-12 07:54 UTC
