### ISSUE TITLE
Unit definition seems to be lost on cart update

### ISSUE THREAD

**Issue by seybsen** [coreshop/CoreShop#1589] opened 2021-02-17 16:19 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes

Pimcore 6.8.9
CoreShop 2.2.9

## 1. add an item with unit != piece to the cart
 
![image](https://user-images.githubusercontent.com/739688/108232653-4a67db80-7143-11eb-8696-e817e74f94b7.png)

## 2. it shows its unit "Carton" in cart
![image](https://user-images.githubusercontent.com/739688/108232764-60759c00-7143-11eb-9b25-f15d562ccf11.png)

## 3. add another item to the cart

![image](https://user-images.githubusercontent.com/739688/108232889-83a04b80-7143-11eb-96d0-d9c1684510d7.png)

## 4. the enormous wooden gloves **don't** show its unit "Carton" anymore

![image](https://user-images.githubusercontent.com/739688/108232943-94e95800-7143-11eb-8d16-9ae8e884f2a0.png)

**Comment by seybsen** [comment] 2021-02-18 15:50
I think this issue is related to https://github.com/coreshop/CoreShop/commit/0c51e19e170dc5272821d27c22773cb066293d94

especially cloning the UnitDefintion without its ID (https://github.com/coreshop/CoreShop/commit/0c51e19e170dc5272821d27c22773cb066293d94#diff-8a03b798c4e3689336e386be677f2d41d3422a133c9286009cb650b1cdfbf3c8R86)

**Comment by dpfaffenbauer** [comment] 2021-02-19 07:34
I am not sure honestly, but don't think a clone is called here. Might have something todo with Pimcore Serialization though....

What Pimcore Version to you use here?

**Comment by dpfaffenbauer** [comment] 2021-02-19 07:34
Sorry, you said it at the top already :D

**Comment by seybsen** [comment] 2021-02-19 07:43
I tested to overwrite the `__clone` in my bundle yesterday and can confirm that this was the cause of the issue. ... but I don't really know what other issues this causes :sweat_smile: 

Do you remember why the clone behaviour was changed in first place?

**Comment by davidhoeck** [comment] 2021-06-03 13:59
@dpfaffenbauer i can confirm, overwriting the `__clone` of the ProductUnitDefinition model removes this issue. The `__clone` is called on serializing the object to store it in the cache - so you're totally right with your thesis. But i am kind of clueless how we should handle that behaviour. 
Here is a screenshot of the trace when `__clone` has been called (PHPStorm debugger)
![image](https://user-images.githubusercontent.com/24294584/120657365-b9640880-c484-11eb-9ffc-c0d350f00b1d.png)

**Comment by dpfaffenbauer** [comment] 2021-06-07 08:29
this really is some chicken-egg kind of problem. On the one side we have to reset the ID for the copy function of unit-definitions. on the other side the cache uses it to serialize the UnitDefinition.

IMO Pimcore really does things completely wrong here... but it is how it is and we have to live with it. I'll try to find a solution.

**Comment by dpfaffenbauer** [comment] 2021-06-07 08:40
https://github.com/coreshop/CoreShop/pull/1649

**Comment by davidhoeck** [comment] 2021-06-07 11:55
@dpfaffenbauer I agree - Pimcore does it completely wrong. But I think it should be fixed with Pimcore X, because they are using Symfony cache there - so it should be a Pimcore 6.x thing.

**Comment by dpfaffenbauer** [comment] 2021-06-14 07:34
fixed

**Closed by dpfaffenbauer** 2021-06-14 07:34 UTC
