### ISSUE TITLE
Wrong Cart Locale

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#652] opened 2018-09-27 09:44 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Sometimes a cart gets populated with a wrong locale code. We think it's happening in the cart blamer process. There has been made some improvements (#620) but this is not enough since a language could be valid but is still wrong because of a wrong context. 

For example: 
- System allows languages `en`, `de`, `de_DE` 
- Shop only enabled for `de_DE`
- Somewhere the request returns a locale `en`
- `isValidLanguage` for `en` is `true`

-> cart receives wrong locale

**Comment by dpfaffenbauer** [comment] 2018-09-27 12:08
Maybe the context refactor changed something? Have you updated and tried that with beta.4 already?

**Comment by dpfaffenbauer** [comment] 2019-03-21 15:35
will close this for now as its not reproduceable

**Comment by solverat** [comment] 2019-04-02 21:09
@dpfaffenbauer after hours of debugging, i finally found it.

The reason is: if you're choosing the "remember me" option, a user may gets re-authorized on root level (eg. www.domain.com). If you're having a multi-locale environment, the locale is not defined yet, so the cart blamer will always assign and persist the default locale, which is "en".

**Comment by dpfaffenbauer** [comment] 2019-04-03 07:44
that is true, I will think about a solution

**Comment by dpfaffenbauer** [comment] 2019-04-29 15:42
only proper solution I could come up with was to assign the right locale before the checkout again. Since the locale is only set during creating the cart, I can't think of another way. WDYT?

**Closed** 2019-07-21 06:51 UTC
Labels: bug
