### ISSUE TITLE
Same Customer Object in Guest Checkout

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#2217] opened 2023-02-16 08:57 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Steps to reproduce:
- Add a product 
- Do guest checkout
- Start new instance (clear browser cache / start in private tab)
- Add a product
- Do guest checkout → **use same email address from you in first checkout**

CoreShop now uses the same object and overwrites its data:

https://github.com/coreshop/CoreShop/blob/c4ddac02c7df4a94f4ee363912ddc9a1322913f3/src/CoreShop/Bundle/CoreBundle/Form/Type/GuestRegistrationType.php#L102

Previously in CS2, every guest checkout created a new customer object, even if the email address already existed.

Don't know if this is a bug, but it feels odd that a guest object can be re-used/overwritten. Plus, if I'm using randomly emails during the guest checkout, it's possible that my data gets assigned to a complete different guest/person.

**Comment by dpfaffenbauer** [comment] 2023-02-16 08:58
The idea behind it was, that if the Guest Customer wants to become a full customer, all of his orders will be linked automatically, even older guest orders

**Comment by dpfaffenbauer** [comment] 2023-05-10 12:40
@solverat since this is expected behaviour, I'll close this.

**Closed by dpfaffenbauer** 2023-05-10 12:40 UTC
